#!/usr/bin/env bash

set -e
echo ''

echo 'Check for xcode command line tools'
if [ -n "$(xcode-select -v)" ]; then 
  echo 'xcode command line tools installed, moving on...'
else 
  echo 'xcode not installed'
  xcode-select --install
fi

echo 'Checking for homebrew'
if ! hash brew; then
  echo 'brew not installed'
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
  echo 'brew is installed, moving on...'
fi

echo 'Install zsh'
brew install zsh

echo 'Setup dotfiles'

DOTFILES_ROOT="${HOME}/.dotfiles"
DOTFILES_REPO="git@github.com:heymackey/dotfiles.git"

if [[ ! -d ${DOTFILES_ROOT} ]]; then
  echo "Cloning repo"
  git clone ${DOTFILES_REPO} ${DOTFILES_ROOT}
fi

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}/.dotfiles"

git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
